### PR TITLE
Fixed bug in calculating the replacement range

### LINKED ISSUE #366: Extra characters while inputting Tamil Text
While Inputting Tamil text with compound letters (கா, கி, etc.), Xi-editor generates additional characters.
The rpc log collected shows that xi-mac making redundant duplicate rpc calls for each compound character insertion.
This causes extra characters to be left in the text.

**Steps to recreate:**
- Enable Tamil99 Keyboard in Input sources
- Press following keys -> hqhslkf
- Expected text -> காகிதம் (U+0B95 U+0BBE U+0B95 U+0BBF U+0BA4 U+0BAE U+0BCD)
- Generated text -> ககாககிததம் (U+0B95 U+0B95 U+0BBE U+0B95 U+0B95 U+0BBF U+0BA4 U+0BA4 U+0BAE U+0BCD)

**Logs:**
The duplicate calls are marked bold.
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"க"}}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"கா"}}}
**{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}**
**{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"கா"}}}**
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"க"}}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"கி"}}}
**{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}**
**{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"கி"}}}**
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"த"}}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"தம"}}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"தம்"}}}
**{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}**
**{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}  
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"தம்"}}}**

### PR DESCRIPTION
**Pull request by SundarTM**
## Related Issues
`closes #366 `

## Summary
The redundant calls ,though inefficient, were done to provide visual feedback to the user while constructing text. The bug was in replaceCharactersInRange while calculating replacement range length.

Updated len to String.utf16.count as in the else case when aString is NSString.

### CODE REVIEW

File: Sources/XiEditor/EditView.swift [hunk 1]
```diff
@@ -274,7 +274,7 @@ final class EditView: NSView, NSTextInputClient, TextPlaneDelegate {
         var replacementRange = aRange
         var len = 0
         if let attrStr = aString as? NSAttributedString {
-            len = attrStr.string.count
+            len = attrStr.string.utf16.count
```
Comment (cmyr) [inline Sources/XiEditor/EditView.swift]: `string.length` is equal to `string.utf16.count`, so maybe we use that so it's clear that these two branches are doing the same thing?

Comment (cmyr) [reply Sources/XiEditor/EditView.swift]: Ah okay I didn't know that the `string` member on `NSAttributedString` was a `String` and not an `NSString`. 😕

This looks good, thanks!
