### PR TITLE
Fix crash when selecting text written in Arabic

### LINKED ISSUE #263: Crash when selecting text written in Arabic
I'm new to this project, I like it.
Today, I was testing writing in Arabic in xi. It shapes the characters correctly, but when I try to select the text it crashes immediately.

Here is a screencast of what happened with me:
output1

Here is a part of the crash report:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.levien.XiEditor           	0x000000010d6dc2e8 $S8XiEditor15TextLineBuilderC5build9fontCacheAA0cD0VAA04FontH0C_tF + 3992 (TextLine.swift:274)
1   com.levien.XiEditor           	0x000000010d718dcb $S8XiEditor8EditViewC6render_9dirtyRectyAA8RendererC_So6CGRectVtF + 4955 (EditView.swift:477)
2   com.levien.XiEditor           	0x000000010d71b4a9 $S8XiEditor8EditViewCAA17TextPlaneDelegateA2aDP6render_9dirtyRectyAA8RendererC_So6CGRectVtFTW + 9
3   com.levien.XiEditor           	0x000000010d6e92df $S8XiEditor14TextPlaneLayerC4draw2in11pixelFormat03forE4Time07displayK0ySo15NSOpenGLContextC_So0m7GLPixelI0CSdSPySo11CVTimeStampaGtFTf4ddddn_n + 607
4   com.levien.XiEditor           	0x000000010d6e82d1 $S8XiEditor14TextPlaneLayerC4draw2in11pixelFormat03forE4Time07displayK0ySo15NSOpenGLContextC_So0m7GLPixelI0CSdSPySo11CVTimeStampaGtFTo + 49
5   com.apple.QuartzCore          	0x00007fff3e0c7fd2 CAOpenGLLayerDraw(CAOpenGLLayer*, double, CVTimeStamp const*, unsigned int) + 1959
6   com.apple.QuartzCore          	0x00007fff3e0c7623 -[CAOpenGLLayer _display] + 565
7   com.apple.AppKit              	0x00007fff3051d67a -[NSOpenGLLayer display] + 240
8   com.apple.QuartzCore          	0x00007fff3e067e7d CA::Layer::display_if_needed(CA::Transaction*) + 633
9   com.apple.QuartzCore          	0x00007fff3e06793b CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 35
10  com.apple.QuartzCore          	0x00007fff3e06692c CA::Context::commit_transaction(CA::Transaction*) + 326
11  com.apple.QuartzCore          	0x00007fff3e0664c5 CA::Transaction::commit() + 487
12  com.apple.QuartzCore          	0x00007fff3e07298a CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 66
13  com.apple.CoreFoundation      	0x00007fff32cf6737 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
14  com.apple.CoreFoundation      	0x00007fff32cf665f __CFRunLoopDoObservers + 511
15  com.apple.CoreFoundation      	0x00007fff32cd89f3 CFRunLoopRunSpecific + 547
16  com.apple.HIToolbox           	0x00007fff31fb8d96 RunCurrentEventLoopInMode + 286
17  com.apple.HIToolbox           	0x00007fff31fb8b06 ReceiveNextEventCommon + 613
18  com.apple.HIToolbox           	0x00007fff31fb8884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
19  com.apple.AppKit              	0x00007fff30269a73 _DPSNextEvent + 2085
20  com.apple.AppKit              	0x00007fff309ffe34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
21  com.apple.AppKit              	0x00007fff3025e885 -[NSApplication run] + 764
22  com.apple.AppKit              	0x00007fff3022da72 NSApplicationMain + 804
23  com.levien.XiEditor           	0x000000010d6cdb29 main + 9 (AppDelegate.swift:80)
24  libdyld.dylib                 	0x00007fff5abb6015 start + 1

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff5acfd20a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5acfc724 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff32cd9ff5 __CFRunLoopServiceMachPort + 341
3   com.apple.CoreFoundation      	0x00007fff32cd9347 __CFRunLoopRun + 1783
4   com.apple.CoreFoundation      	0x00007fff32cd89b7 CFRunLoopRunSpecific + 487
5   com.apple.AppKit              	0x00007fff303a6fc4 _NSEventThread + 184
6   libsystem_pthread.dylib       	0x00007fff5aece661 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff5aece50d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff5aecdbf9 thread_start + 13

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff5aecdbdc start_wqthread + 0
1   ???                           	0x41c0a8d86f23295f 0 + 4737972455524739423

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff5aecdbdc start_wqthread + 0
1   ???                           	0x0000000100000038 0 + 4294967352

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x8c3cd53cb712002c  rbx: 0x00006080001b73e0  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00007fed3ae143f8  rsi: 0x0000000000000000  rbp: 0x00007ffee253ad80  rsp: 0x00007ffee253abd0
   r8: 0x0000000000000001   r9: 0x0000000000000000  r10: 0x0000000000000017  r11: 0x00007fed3af25d20
  r12: 0x000000010dc55c90  r13: 0x0000000000000001  r14: 0x0000000000000017  r15: 0x000000000000000e
  rip: 0x000000010d6dc2e8  rfl: 0x0000000000010203  cr2: 0x000000011063c000
  
Logical CPU:     4
Error Code:      0x00000000
Trap Number:     6

```

### PR DESCRIPTION
**Pull request by mmatoszko**
This should fix #263.

Right now the app crashes while selecting text in Arabic using the following snippet:

```
Selecting characters written in English works fine, 
but when I try to select characters written in Arabic, it crashes

The following line is written in Arabic, it's shaped correctly without any issue
هذا السطر مكتوب بالعربية ولا مشكلة في الكتابة أبدًا
```

After the change the crash does not occur.

This is my first contribution to the project. Please be kind and let me know if there's any documentation missing with this one 😄

### CODE REVIEW

File: XiEditor/XiTextPlane/TextLine.swift [hunk 1]
```diff
@@ -271,5 +271,5 @@ func argbToFloats(argb: UInt32) -> (GLfloat, GLfloat, GLfloat, GLfloat) {
 func getCtLineRange(_ ctLine: CTLine, _ range: CountableRange<Int>) -> Range<GLfloat> {
     let start = GLfloat(CTLineGetOffsetForStringIndex(ctLine, range.startIndex, nil))
     let end = GLfloat(CTLineGetOffsetForStringIndex(ctLine, range.endIndex, nil))
-    return start ..< end
+    return Range(uncheckedBounds: (lower: start, upper: end))
```
Comment (raphlinus) [inline XiEditor/XiTextPlane/TextLine.swift]: Good catch tracking it down to this. That said, I have some concerns.

* Does `uncheckedBounds` just get rid of the assert, but still violate the invariant, or is it actually valid to have a range with `upper < lower`?

* What will this do in the case of mixed ltr and rtl runs? Without digging right now, my guess would be that the signature of this function needs to be changed to return a list of ranges, and the logic needs to be updated to sense direction changes in the interior, not just sample the endpoints.

It's possible though that this is future work, and we accept some loss of accuracy for selections of bidi text for now. If my concern about the range invariant is true, then maybe we want lower to be min(start, end) and upper to be max(start, end).

Comment (mmatoszko) [reply XiEditor/XiTextPlane/TextLine.swift]: You're right, it's even nicely documented 😄
```
    /// Because this initializer does not perform any checks, it should be used
    /// as an optimization only when you are absolutely certain that `lower` is
    /// less than or equal to `upper`. Using the half-open range operator
    /// (`..<`) to form `Range` instances is preferred.
```
I updated the solution according to your suggestion.

To be honest I'm not yet sure how to approach bidi correctly. This is my first attempt to text editor development and I don't feel like I've got enough knowledge on the topic yet.
